### ISSUE TITLE
Debugging a hang

### ISSUE THREAD

**Issue by ivoras** [darold/pgbadger#454] opened 2018-11-09 19:15 UTC
Hi,

Something in my log file causes pgbadger to hang - or at least it appears hung: it consumes 100% of a CPU, stops outputting anything even with -v, and, surprisingly, cannot be terminated with Ctrl-C or SIGTERM, but must be forced with SIGKILL.

I'm not familiar with Perl, so is there anything I can do to resolve this? This is on CentOS 6 with PostgreSQL 9.3, I'm using pgbadger 10.1, and normally I'm starting it only with the log filename as a parameter. Here's the output of a "-v" run:

```
temp$ pgbadger -v postgresql.log-20181109
DEBUG: Autodetected log format 'stderr' from postgresql.log-20181109
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Autodetected log format 'stderr' from postgresql.log-20181109
DEBUG: Autodetected log format 'stderr' from postgresql.log-20181109
DEBUG: pgBadger will use log format stderr to parse postgresql.log-20181109.
DEBUG: Starting to parse log file: postgresql.log-20181109
DEBUG: Starting reading file postgresql.log-20181109...15198541 (0.00%), queries: 0, events: 0
DEBUG: Start parsing at offset 0 of file postgresql.log-20181109 to 615198541
```
then it out's a few "unrecognized line" errors, which are fine because we're using pgaudit, and then it simply hangs.

**Comment by darold** [comment] 2018-11-09 20:55
I don"t see any reason that can make pgbadger hangs. Please send the log file to my private address < gilles AT darold DOT net > that will be helpful.

**Comment by darold** [comment] 2018-12-08 16:31
I'm closing this issue, without a log to reproduce the problem I do not see what part of the code can hang pgBadger.

**Closed by darold** 2018-12-08 16:31 UTC

**Comment by peruuparkar** [comment] 2019-07-29 15:50
I see similar issue at my end, PgBadger just keep on working without making any progress at all. In my case it ran for 2 days, but no output. CPU reaches 100% all the time.  Here are details at my end,

Postgres server version : 11.1  ( pgdg16.04+1), server 11.1)
Operating system : Ubuntu 11.4-1
Client - where PgBadger running :- Mac OS High Sierra ( 10.13.6)
Client HW : Intel I7 2.2 GHz
Client ram: 16 GB
pgbadger version:  pgBadger version 11.0


------------------- Output from PgBadger ---
Bhushans-MacBook-Pro:Downloads bhushanuparkar$ ls -lt postgres.log.20190725
-rw-r--r--  1 bhushanuparkar  staff  8942010 Jul 29 08:24 postgres.log.20190725
Bhushans-MacBook-Pro:Downloads bhushanuparkar$ pgbadger --prefix '%t:%r:%u@%d:[%p]:' -f stderr -v postgres.log.20190725
DEBUG: timezone not specified, using 25200 seconds
DEBUG: Output 'html' reports will be written to out.html
DEBUG: Starting progressbar writer process
DEBUG: Autodetected log format 'stderr' from postgres.log.20190725
DEBUG: pgBadger will use log format stderr to parse postgres.log.20190725.
DEBUG: Processing log file: postgres.log.20190725
DEBUG: Starting reading file postgres.log.20190725...
DEBUG: Start parsing postgresql log at offset 0 of file postgres.log.20190725 to 8942010
[>                        ] Parsed       0 bytes of 8942010 (0.00%), queries: 0, events: 0

**Comment by peruuparkar** [comment] 2019-07-29 15:54
I can upload the above postgres log file, but it contains client sensitive data. Could you please a suggest a way to "Anonymize Sensitive PostgreSQL Data" ?

**Comment by darold** [comment] 2019-07-29 17:23
Hi,

Please send the log to my private email < gilles AT darold DOT net > you will have complete privacy. You can also try to split the file to see at what point the hang appears and just send this part. I have no simple idea in how to anonymize and if after that the problem still occurs.

**Comment by darold** [comment] 2019-08-01 21:28
Thanks for the log, the problem is that you have very long queries > 7Mb and a commit (5e88446) introduced in v11 release does more harm than good. Commit a87fd55 fix this issue by reverting this commit. Please use latest development code and let me know, your queries will be truncated at 1Kb by default but as it is INSERT with multiple values this is not problematic I guess.

**Comment by chad-iris** [comment] 2019-08-07 01:28
I have a log file that causes pgbadger to hang (with 100% cpu usage, seemingly without end) as  described in this issue.  I pulled the latest changes, up to da91dad0663e5483a09f1b516c2221660c688d7b, and it does not fix the problem.  I do not see any commit a87fd55 on the master branch for what it's worth.

The only way I can get pgbadger to parse the file is to use `--exclude-query="^INSERT"`, to skip the INSERT queries.  I would really rather have truncated queries that include all statements/queries.

**Comment by chad-iris** [comment] 2019-08-07 01:37
I also tried to set the `--maxlength` option to small values, but that had no effect.

**Comment by darold** [comment] 2019-08-07 07:21
Damned, sorry I forgot to push this commit. Please download latest code again.

**Comment by chad-iris** [comment] 2019-08-07 16:27
Confirmed working with latest master, thanks @darold !

**Comment by peruuparkar** [comment] 2019-08-07 17:34
+ 1

Latest patch resolves the issue  at my end.

Sincerely,
Bhushan
Urgency to be patience !
