### ISSUE TITLE
Multiline queries are truncated on v11.6

### ISSUE THREAD

**Issue by fpietka** [darold/pgbadger#680] opened 2021-08-11 07:02 UTC
Hi,

I had the same issue as #678 so I had to build from master to get reports again.
Since then queries that are on multiple line of logs aren't joined anymore, so they are are more difficult to pinpoint.

My command didn't change in the meantime. I do hourly incremental reports (can't do full at once because of memory consumption):
```
pgbadger -j 8 -f logplex --dbname=XXXX --incremental --exclude-query="^(COPY|COMMIT|BEGIN|SELECT 1)" --exclude-query="(pg_start_backup|pg_stop_backup|pg_catalog|pg_stat_statements|pg_catalog.pg_stat_archiver)" --outdir /home/ubuntu/pgbadger --noreport logs/$date.log
```
then I generate a full report once per day:
```
pgbadger --incremental --no-week -H /home/ubuntu/pgbadger/ -l /home/ubuntu/pgbadger/ /home/ubuntu/pgbadger/$date_folder/*.bin
```

**Comment by fpietka** [comment] 2021-09-06 08:55
now my problem appear on v11.6

**Comment by fpietka** [comment] 2021-09-06 10:24
hmm, I think you can close this issue, it seems my problem is more related to rsyslog:
https://serverfault.com/questions/802541/why-does-rsyslog-replace-tabs-with-011/802984

Do you think it would make sense to handle this `#011` in pgbadger?

**Comment by darold** [comment] 2021-09-06 17:12
I don't think it is related to this `#011`, at worst they will not be replaced in the query. The problem is that I can not reproduce this issue, if you can send me a log that have this issue to my private email < gilles AT darold DOT net > I'm sure I can fix it easily. Or if you prefer I think pgbench is using multi-line query so you can create a public logfile to post here.

**Comment by darold** [comment] 2021-09-09 16:46
Commit a5bae25 might fix this issue. The problem was not related to multi-line but to Heroku logplex format change. I am surprised that pgbadger was able to report something, with your sample I was not reporting anything, anyway that's fixed now. Thanks for the report.

**Closed** 2021-09-10 18:02 UTC
