### ISSUE TITLE
Cutted query where CRLF and tab in query

### ISSUE THREAD

**Issue by systequ** [darold/pgbadger#779] opened 2023-05-24 09:50 UTC
I have a lot of  cutted queries after update to pgBadger 12.1:
After checking  logs it happened when its CRLF and tab in new line:
Sample:

> g.EXAMPLE_5 AS COL5 , CR LF
> ⟶g.EXAMPLE_6 AS COL6 ,

In "Time consuming queries" the query ends after g.EXAMPLE_5 AS COL5

>select [....]  g.example_5 as col5, ;

**Comment by darold** [comment] 2023-05-24 10:35
Please attach a file with some lines from your log that are related to the problem. They can be anonymized.

**Comment by systequ** [comment] 2023-05-24 10:51
[779.log](https://github.com/darold/pgbadger/files/11553631/779.log)

**Comment by darold** [comment] 2023-05-25 13:10
I'm not able to reproduce with the sample, what pgbadger command line are you using?

**Comment by systequ** [comment] 2023-05-25 13:36
> pgbadger -v -t 40 --extra-files --format stderr --jobs 8 --timezone +2 --incremental --outdir /var/www/html/pgbadger11/customer/ --html-outdir /var/www/html/pgbadger11/customer/  /db/pgbadger11/customer/* --exclude-appname "pg_dump"  --exclude-appname "pgbench" --exclude-query "^(VACUUM|ANALYZE)"

**Comment by darold** [comment] 2023-05-25 13:44
How about if you add ` -p '%t [%p]: [%l-1] app=%a '` to your pgbadger command?

**Comment by systequ** [comment] 2023-05-25 14:05
still the same

**Comment by darold** [comment] 2023-05-25 15:13
do you have the same with the sample log you have provided?

**Comment by systequ** [comment] 2023-05-26 08:57
Example works:
![Screenshot-20230526103220-1020x310](https://github.com/darold/pgbadger/assets/64026229/3907e8e3-0639-4b42-b387-2d587a3bc8e9)
Still the same problem with analyze of all day logs file.

**Comment by darold** [comment] 2023-05-27 06:22
I have the same, the query is complete, you can click on the query to see the scroll cursor or double click on the query to see the formatted query and scroll to see all the query.

**Comment by systequ** [comment] 2023-06-05 10:41
With full log i still have the same problem. 
Today i tried on the same full day log file 
with pgbadger 11.8:
![11_8_Screenshot-20230605123704-1051x251](https://github.com/darold/pgbadger/assets/64026229/5f7d8d30-e108-419d-8b0b-cda10f77fb31)
and with 12.1 
![12_1_Screenshot-20230605123624-1079x267](https://github.com/darold/pgbadger/assets/64026229/0e9b4887-8f51-4228-8e4c-72190c3c0240)
In the 11.8 problematic queries are not cutted.

**Comment by darold** [comment] 2024-02-07 18:30
Closing, not reproducible with latest development code.

**Closed by darold** 2024-02-07 18:30 UTC
