### ISSUE TITLE
pgbadger of master branch (and v10.x) hang up on Windows after the progress bar message as follow

### ISSUE THREAD

**Issue by JMLessard** [darold/pgbadger#505] opened 2019-06-04 21:24 UTC
pgbadger of master branch (and other v10.x too) hang up after the progress bar message as follow on Windows
```
C:\pgbadger>perl pgbadger -p "%m [%p]: " -f stderr -v D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log -o c:/temp/out.html
DEBUG: Output 'html' reports will be written to c:/temp/out.html
DEBUG: Autodetected log format 'stderr' from D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log
DEBUG: pgBadger will use log format stderr to parse D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log.
DEBUG: Starting progressbar writer process
```
I installed pgbadger of v9 branch and it work fine
```
C:\pgbadger-9>perl pgbadger -p "%m [%p]: " -f stderr -v D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log -o c:/temp/out.html
DEBUG: Autodetected log format '' from D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log
DEBUG: Output 'html' reports will be written to c:/temp/out.html
DEBUG: Autodetected log format '' from D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log
DEBUG: Autodetected log format '' from D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log
DEBUG: pgBadger will use log format stderr to parse D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log.
DEBUG: Starting to parse log file: D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log
DEBUG: Starting reading file D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log...
DEBUG: Start parsing postgresql log at offset 0 of file D:/PostgreSQL/data/pg_log/postgresql-2019-06-04_175527.log to 4345
...
```

**Comment by darold** [comment] 2019-06-13 07:40
Commit 6bd6639 fixes this issue, the progress bar was done like on Unix system through a fork and a pipe. pgBadger can not fork and use pipe on Windows.

**Comment by JMLessard** [comment] 2019-06-13 13:35
Thanks for the fix.
It hangs now after parsing and there is no out.html file created.

```
DEBUG: Output 'html' reports will be written to c:/temp/out.html
DEBUG: Autodetected log format 'stderr' from c:/temp/postgresql-2019-06-04_175527.log
DEBUG: pgBadger will use log format stderr to parse c:/temp/postgresql-2019-06-04_175527.log.
DEBUG: Processing log file: c:/temp/postgresql-2019-06-04_175527.log
DEBUG: Starting reading file c:/temp/postgresql-2019-06-04_175527.log...0, events: 0
DEBUG: Start parsing postgresql log at offset 0 of file c:/temp/postgresql-2019-06-04_175527.log to 3892
[=======================> ] Parsed 3859 bytes of 3892 (99.15%), queries: 0, events: 0
```

**Comment by darold** [comment] 2019-06-13 13:47
Last commit b8f53ea fixes an other case where the progress bar pipe can still be called on Windows. I'm not sure that this is the reason of this new hang but please give it a try. I'm sorry but I do not have a Windows box to be able to test. Also if the problem is not fixed with this new commit can you confirm that pgbadger is working well when the quiet mode is used  (`-q` option)?

**Comment by JMLessard** [comment] 2019-06-13 14:11
It still hang even in quite mode.

```
C:\pgbadger>perl pgbadger c:/temp/postgresql-2019-06-04_175527.log -o c:/temp/out.html
[=======================> ] Parsed 3859 bytes of 3892 (99.15%), queries: 4, events: 5
Received terminating signal (INT).
C:\pgbadger>perl pgbadger -q c:/temp/postgresql-2019-06-04_175527.log -o c:/temp/out.html
```
No problem, I can test on Windows.
Thanks again

**Comment by darold** [comment] 2019-06-13 14:25
Well no more idea to solve this problem, I need to find a VM to try to reproduce.

**Comment by darold** [comment] 2019-06-17 19:55
Got a working Windows VM, commit d02bebd fixes this issue.

**Comment by JMLessard** [comment] 2019-06-18 13:42
Nice, thank you

**Comment by JMLessard** [comment] 2019-06-18 14:14
The output file is generated properly but the content is empty.
Find attached a small log file with few queries.
[postgresql-2019-06-04_175527.zip](https://github.com/darold/pgbadger/files/3301875/postgresql-2019-06-04_175527.zip)

Noting is reported in query and temp file.

I am missing something?
Would you like that I open another issue?

**Comment by darold** [comment] 2019-07-18 11:14
I'm reopening the issue before I totally forgot to fix Windows port.

**Comment by darold** [comment] 2019-09-14 10:27
Commit f459e49 fix the windows port.

**Closed by darold** 2019-09-14 10:27 UTC
