### ISSUE TITLE
no data in "write traffic" graph

### ISSUE THREAD

**Issue by diogithub** [darold/pgbadger#601] opened 2020-07-10 12:49 UTC
Dear Darold, 

I know that this topic has been already discussed but I cannot realize why I do not have data in that graph while I have insertions/updates in the db. All the other graphs are working fine..

I create the reports as follows : 
/usr/local/bin/pgbadger -I -j 4 --prefix '%m [%p]: db=%d,user=%u,app=%a,client=%r ' /pgbadger_logs/postgresql*.log -O /pgbadger_reports/

In postgresql.conf  I have the following configurations:

parameter | setting | unit
lc_messages | C |  
log_autovacuum_min_duration | 0 | ms
log_checkpoints | on |  
log_connections | on |  
log_disconnections | on |  
log_error_verbosity | default |  
log_line_prefix | %m [%p]:   db=%d,user=%u,app=%a,client=%r |  
log_lock_waits | on |  
log_min_duration_statement | 1000 | ms
log_temp_files | 0 | kB

Please let me know if something is wrong from my side.

![writes_graph](https://user-images.githubusercontent.com/57260423/87156601-9b6a4400-c2c5-11ea-8a01-e1e811a56743.png)

**Comment by darold** [comment] 2020-07-18 09:27
This is a duplicate of #599, the "INSERT/UPDATE/DELETE Traffic" graph unlike the previous in this page, doesn't report the min/max/mean of the write queries but the average per 5 minutes. If they are all at 0 this is because the ratio `queries / 300s` is near or equal to 0.

**Closed** 2020-07-18 09:27 UTC
