### ISSUE TITLE
scheduling  pgbadger every day

### ISSUE THREAD

**Issue by mcunault** [darold/pgbadger#545] opened 2019-11-22 09:22 UTC
PostgreSQL 11.5, pgabdger 11.1
Hello,
I want pgbadger to parse log every day between 8 AM and 18 PM.
I write :
`perl.exe pgbadger c:/.../log/postgresql-3.log -I --retention 2 -d activite -b "08:00:00" -e "18:00:00" -O c:/.../pgbadger `
It returns : 

> unrecognized signal name "USR2" at pgabdger line 3932.

What doest it mean ?
Thanks

**Comment by Inrap** [comment] 2019-11-22 09:43
These are the debugging lines. I noticed an out.html in the pgbadger directory instead of the one specified by -O.
![image](https://user-images.githubusercontent.com/32261793/69415340-b6774c00-0d14-11ea-87a2-7ac9336b217b.png)
I am a bit confused.

**Comment by darold** [comment] 2019-11-22 10:05
Hi,

Normally USR2 signal is not used on Windows operating system but there is still a call that do not respect this exception. Commit d5558c9 might fix it.

Please use latest development code and let me know if the issue with output dir persist.

**Comment by Inrap** [comment] 2019-11-22 10:58
It sounds good for USR2. Thanks

But I still can't get the log be parsed between 08:00:00 and 18:00:00 : 
- only index.html is created when I use the task scheduler : 
 `perl.exe pgbadger C:/"Program Files"/PostgreSQL/11/data/log/postgresql-1.log -I --retention 2 -b "08:00:00" -e "18:00:00" -d activite -O C:/ms4w/Apache/site/pgbadger `
`perl.exe pgbadger C:/"Program Files"/PostgreSQL/11/data/log/postgresql-2.log -I --retention 2 -b 08:00:00" -e "18:00:00" -d activite -O C:/ms4w/Apache/site/pgbadger`
`...`
- I test in cmd line, here what I get and nothing is created : 
![image](https://user-images.githubusercontent.com/32261793/69420094-4a014a80-0d1e-11ea-9a4d-4ca04c60f8a3.png)

**Comment by darold** [comment] 2019-12-01 09:47
The problem is that pgBadger port to Windows is broken, it still need to be fixed. I don't have time for the moment but this is a high priority for next release.

**Comment by darold** [comment] 2020-03-04 06:15
Fixed in last development code, a new release is coming.

**Closed by darold** 2020-03-04 06:15 UTC
