### ISSUE TITLE
Empty reports generated after upgrading RDS to postgres 12.x

### ISSUE THREAD

**Issue by Play9win** [darold/pgbadger#625] opened 2020-12-03 09:07 UTC
Hello,

I have configured pgbadger as a docker container for my RDS instance running postgresql. Just a month ago I upgraded the postgres to version 12.x, since then it has started giving me empty reports.

Is the version not supported? Is there anything else I need to do ?

I use the following command to generate report in the container and then use docker cp to move it outside and read it on my system.

`sudo docker run --name container_name -e START_TIME="$START_TIME" -e END_TIME="$END_TIME" -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" -e REGION=$REGION -e S3_BUCKET=$S3_BUCKET -e DB_NAME=$DB_NAME dockerhub_image_pgbadger
`

**Comment by darold** [comment] 2020-12-03 09:16
PostgreSQL 12 is fully supported by pgBadger, I don't know about the pgbadger docker image but I guess that the problem is more related to the plog_line_prefix that might have changed. Post a line of you log file so that we can check.

**Comment by darold** [comment] 2020-12-12 09:09
Should I close this issue?

**Closed** 2020-12-16 07:30 UTC
