### ISSUE TITLE
Mess in reports when using --exclude-user/--exclude-appname parameters

### ISSUE THREAD

**Issue by ccppprogrammer** [darold/pgbadger#614] opened 2020-10-13 14:52 UTC
When I use --exclude-user/--exclude-appname, pgbadger generates "Top Queries" reports that include queries from the excluded user/app and which are combined with the main queries.

pgbadger command line:
```
PGSQL_LOG_DATE=`date --date="1 days ago" +%Y-%m-%d`
PGBADGER_BIN="/usr/bin/pgbadger"
PGSQL_LOG_DIR="/var/log/postgresql"
PGSQL_LOG_FILENAME="postgresql-${PGSQL_LOG_DATE}*.log"
PGBADGER_PREFIX="%m [%p] %q[user=%u,db=%d,app=%a,host=%h] "
PGBADGER_OUTPUT_FILENAME="${PGSQL_LOG_DIR}/pgbadger/${PGSQL_LOG_DATE}.html"

${PGBADGER_BIN} --pid-dir /tmp/ --timezone +3 --jobs 10 -q `find ${PGSQL_LOG_DIR}/ -name "${PGSQL_LOG_FILENAME}"` --prefix "${PGBADGER_PREFIX}" -o ${PGBADGER_OUTPUT_FILENAME} --exclude-user "datadog" --exclude-appname "datadog-agent"
```

"Top Queries" -- "Time consuming queries". 
As you can see, after "regular query" there is another query from datadog user which I excluded in command line:
```
<regular query> <stat query #1> <stat query #2> <stat query #3>
```
```
<regular query>
SELECT schemaname, count(*) FROM ( SELECT schemaname FROM pg_stat_user_tables ORDER BY schemaname, relname LIMIT ?) AS subquery GROUP BY schemaname 
SELECT mode, locktype, pn.nspname, pd.datname, pc.relname, count(*) AS lock_count FROM pg_locks l JOIN pg_database pd ON (l.database = pd.oid) JOIN pg_class pc ON (l.relation = pc.oid) LEFT JOIN pg_namespace pn ON (pn.oid = pc.relnamespace) WHERE (relname ~ ?) AND l.mode IS NOT NULL AND pc.relname NOT LIKE ? GROUP BY pd.datname, pc.relname, pn.nspname, locktype, mode 
SELECT relname, schemaname, seq_scan, seq_tup_read, idx_scan, idx_tup_fetch, n_tup_ins, n_tup_upd, n_tup_del, n_tup_hot_upd, n_live_tup, n_dead_tup FROM pg_stat_user_tables WHERE (relname ~ ?);
```

![image](https://user-images.githubusercontent.com/7936874/95876651-f3f52580-0d7b-11eb-8986-627318fb1b65.png)

PostgreSQL log entries for excluded user/appname:
```
2020-10-12 19:00:13.536 EDT [2925] [user=datadog,db=XXX,app=datadog-agent,host=::1] LOG:  duration: 1.827 ms  statement: 
        SELECT schemaname, count(*) FROM
        (
        SELECT schemaname
        FROM pg_stat_user_tables
        ORDER BY schemaname, relname
        LIMIT 200
        ) AS subquery GROUP BY schemaname
            

```
```
2020-10-12 19:01:28.538 EDT [2925] [user=datadog,db=XXX,app=datadog-agent,host=::1] LOG:  duration: 1.127 ms  statement: 
        SELECT mode,
               locktype,
               pn.nspname,
               pd.datname,
               pc.relname,
               count(*) AS lock_count
          FROM pg_locks l
          JOIN pg_database pd ON (l.database = pd.oid)
          JOIN pg_class pc ON (l.relation = pc.oid)
          LEFT JOIN pg_namespace pn ON (pn.oid = pc.relnamespace)
         WHERE ( relname ~ '.*' )
           AND l.mode IS NOT NULL
           AND pc.relname NOT LIKE 'pg_%%'
         GROUP BY pd.datname, pc.relname, pn.nspname, locktype, mode

```
```
2020-10-12 19:01:13.542 EDT [2925] [user=datadog,db=XXX,app=datadog-agent,host=::1] LOG:  duration: 1.860 ms  statement: 
        SELECT relname,schemaname,seq_scan, seq_tup_read, idx_scan, idx_tup_fetch, n_tup_ins, n_tup_upd, n_tup_del, n_tup_hot_upd, n_live_tup, n_dead_tup
          FROM pg_stat_user_tables
         WHERE ( relname ~ '.*' )

```

**Comment by darold** [comment] 2020-11-06 18:24
I'm not able to reproduce the problem, can you confirm that the issue is still present with latest development code?

**Comment by darold** [comment] 2020-11-24 05:39
Without answer I'm considering that the problem is solved with latest pgbadger code, closing.

**Closed by darold** 2020-11-24 05:39 UTC
